Repository MeshInspector/MeshLib, pull requests merged in 2024-12, with the labels that each got.

#3800 Fix c# examples build
  .github/workflows/build-test-windows.yml
  .gitignore
  examples/c-sharp-examples/c-sharp-examples.csproj
  test_regression/conftest.py
  test_regression/helpers/common_helpers.py
  test_regression/test_doc_samples/test_c_sharp_samples.py
Labels: full-ci

#3834 Pip build any branch
  .github/workflows/pip-build.yml
  .github/workflows/release-tests.yml
  .github/workflows/test-distribution.yml
  .github/workflows/test-pip-build.yml
Labels: test-pip-build

#3841 I5338 fix docs structure
  doxygen/APIPage.dox
  scripts/doxygen/generate_doxygen_layout.sh
Labels: documentation, update-doc

#3848 Remove unwanted python module copies from the distribution.
  scripts/make_install_folder.py
Labels: test-pip-build

#3851 update docs thirdparty and links
  doxygen/About.dox
  doxygen/CppSetupGuide.dox
  doxygen/ThirdpartyList.dox
Labels: update-doc

#3854 fix script to build DoxygenLayouts
  doxygen/APIPyPage.dox
  doxygen/layout_templates/API_part.xml
  scripts/doxygen/generate_doxygen_layout.sh
Labels: update-doc

#3860 Cmake integration doxygen page
  doxygen/CmakeSetupGuide.dox
  doxygen/DoxygenLayout.xml
  doxygen/GettingStarted.dox
  doxygen/layout_templates/base_struct.xml
Labels: update-doc

#3838 Enable Cuda in the bindings.
  .github/workflows/pip-build.yml
  CMakeLists.txt
  scripts/build_wheel.sh
  scripts/distribution.sh
  scripts/mrbind/compiler_only_flags.txt
  scripts/mrbind/generate.mk
  scripts/mrbind/mrbind_commit.txt
  scripts/mrbind/mrbind_flags.txt
  scripts/wheel/build_constants.py
  scripts/wheel/setup.py
  source/MRCuda/MRCuda.vcxproj
  source/MRCuda/MRCuda.vcxproj.filters
  source/MRCuda/MRCudaContoursDistanceMap.cpp
  source/MRCuda/MRCudaFastWindingNumber.h
  source/MRCuda/MRCudaPointsToMeshProjector.h
  source/MRCuda/MRCudaSolarRadiation.cpp
  source/MRCuda/MRCudaSolarRadiation.h
  source/MRMesh/MRPointsToMeshProjector.h
  source/MRVoxels/MRPointsToDistanceVolume.h
  source/mrmeshnumpy/MRPythonNumpyExposing.cpp
Labels: test-pip-build

#3861 Extend documentation of the subvoxel mesh correction.
  source/MRVoxels/MRMoveMeshToVoxelMaxDeriv.h
Labels: update-doc

#3867 Add offset cuda sample
  doxygen/examples/CudaOffset.dox
  doxygen/examples/Examples.dox
  examples/python-examples/CudaOffset.dox.py
Labels: update-doc

#3882 update build documentations workflow
  .github/workflows/update-docs.yml
  doxygen/layout_templates/API_part.xml
  scripts/doxygen/generate_doxygen_layout.sh
Labels: update-doc

#3891 reworked to using relative url paths
  doxygen/APIPage.dox
  scripts/doxygen/generate_doxygen_layout.sh
Labels: update-doc
