Repository MeshInspector/MeshLib, pull requests merged in 2024-11, with the labels that each got.

#3615 fix deploying documentations workflow
  .github/workflows/build-test-distribute.yml
  .github/workflows/update-docs.yml
Labels: full-ci

#3620 Add plugin example into MeshLib distribution
  .github/workflows/build-test-distribute.yml
  example_plugin/MyPlugin.cpp
  example_plugin/MyPlugin.items.json
  example_plugin/MyPlugin.ui.json
  example_plugin/example_plugin.sln
  example_plugin/example_plugin.vcxproj
  example_plugin/readme.md
  example_plugin/resource/icons/X0_5/My State Tool.png
  example_plugin/resource/icons/X0_5/My Tool.png
  example_plugin/resource/icons/X0_75/My State Tool.png
  example_plugin/resource/icons/X0_75/My Tool.png
  example_plugin/resource/icons/X1/My State Tool.png
  example_plugin/resource/icons/X1/My Tool.png
  example_plugin/resource/icons/X3/My State Tool.png
  example_plugin/resource/icons/X3/My Tool.png
  scripts/install_tools.py
  scripts/zip_distribution.py
Labels: full-ci

#3625 Test example plugin compilation on distribute
  .github/workflows/build-test-distribute.yml
  .github/workflows/build-test-macos.yml
  .github/workflows/build-test-windows.yml
  example_plugin/example_plugin.vcxproj
  example_plugin/readme.md
Labels: full-ci

#3631 Update examples in documentation to new style
  doxygen/HowToExamples.dox
  doxygen/examples/BasedApplication.dox
  doxygen/examples/FreeFormDeformation.dox
  doxygen/examples/GlobalRegistration.dox
  doxygen/examples/HowToExamples.dox
  doxygen/examples/LaplacianExample.dox
  doxygen/examples/MeshBoolean.dox
  doxygen/examples/MeshDecimate.dox
  doxygen/examples/MeshExport.dox
  doxygen/examples/MeshExtrude.dox
  doxygen/examples/MeshFillHole.dox
  doxygen/examples/MeshICP.dox
  doxygen/examples/MeshLoadSave.dox
  doxygen/examples/MeshModification.dox
  doxygen/examples/MeshOffset.dox
  doxygen/examples/MeshResolveDegenerations.dox
  doxygen/examples/MeshStitchHole.dox
  doxygen/examples/NoiseDenoiseExample.dox
  doxygen/examples/Numpy.dox
  doxygen/examples/NumpyTriangulation.dox
  doxygen/examples/Plotly.dox
  doxygen/examples/Triangulation.dox
  examples/MeshBooleanExample.dox
  examples/c--sharp-example/Examples.dox
  examples/c-examples/Examples.dox
  examples/cpp-examples/Examples.dox
  examples/python-examples/Examples.dox
Labels: full-ci

#3519 bump github runner to macos-13
  .github/workflows/release-tests.yml
  .mailmap
Labels: full-ci

#3644 Updated Documentation Layout
  doxygen/About.dox
  doxygen/CSharpSetupGuide.dox
  doxygen/CodingStyleHelp.dox
  doxygen/CppSetupGuide.dox
  doxygen/DataModel.dox
  doxygen/DoxygenLayout.xml
  doxygen/FirstPluginTutorial.dox
  doxygen/GettingStarted.dox
  doxygen/HomePage.dox
  doxygen/License.dox
  doxygen/PythonSetupGuide.dox
  doxygen/Spaces.dox
  doxygen/StatePluginsHelp.dox
  doxygen/ThirdpartyList.dox
  doxygen/Tutorials.dox
  doxygen/examples/Examples.dox
Labels: full-ci

#3645 missing picture in plotly example has been added
  doxygen/DoxygenLayout.xml
  doxygen/examples/BasedApplication.dox
  doxygen/examples/Examples.dox
  doxygen/examples/Plotly.dox
  doxygen/examples/ViewerExample.dox
Labels: full-ci

#3647 fix example documentations
  doxygen/examples/FreeFormDeformation.dox
  doxygen/examples/LaplacianExample.dox
  doxygen/examples/NoiseDenoiseExample.dox
  doxygen/examples/Triangulation.dox
Labels: full-ci

#3651 Remove dotnet dist
  .github/workflows/build-test-distribute.yml
  .github/workflows/build-test-windows.yml
Labels: full-ci

#3657 Fix macos distribution test
  .github/workflows/test-distribution.yml
Labels: full-ci

#3664 small text fixes in exmaple docs
  doxygen/examples/BasedApplication.dox
  doxygen/examples/FreeFormDeformation.dox
  doxygen/examples/LaplacianExample.dox
  doxygen/examples/MeshBoolean.dox
  doxygen/examples/MeshDecimate.dox
  doxygen/examples/MeshExport.dox
  doxygen/examples/MeshExtrude.dox
  doxygen/examples/MeshFillHole.dox
  doxygen/examples/MeshICP.dox
  doxygen/examples/MeshLoadSave.dox
  doxygen/examples/MeshModification.dox
  doxygen/examples/MeshOffset.dox
  doxygen/examples/MeshStitchHole.dox
  doxygen/examples/NoiseDenoiseExample.dox
  doxygen/examples/Triangulation.dox
  doxygen/examples/ViewerExample.dox
Labels: full-ci

#3678 test simple tag for documentation update
  .github/workflows/build-test-distribute.yml
Labels: update-doc

#3682 docs/small_update_and_fixes
  doxygen/APIPage.dox
  doxygen/About.dox
  doxygen/CSharpSetupGuide.dox
  doxygen/PackageOverview.dox
  doxygen/examples/Examples.dox
Labels: update-doc

#3676 fixed the code style of the example
  examples/c-examples/MeshBoolean.dox.c
  examples/c-examples/MeshDecimate.dox.c
  examples/c-examples/MeshFillHole.dox.c
  examples/c-examples/MeshImportExport.dox.c
  examples/c-examples/MeshOffset.dox.c
  examples/c-examples/MeshResolveDegenerations.dox.c
  examples/cpp-examples/MeshDecimate.dox.cpp
Labels: full-ci

#3690 MeshVoxelsConverter: Add unit test
  source/MRVoxels/MRBoolean.cpp
Labels: full-ci

#3707 Download a specific Clang version on Windows.
  .github/workflows/build-test-windows.yml
  docker/ubuntu20Dockerfile
  docker/ubuntu22Dockerfile
  docker/ubuntu24Dockerfile
  scripts/mrbind/README.md
  scripts/mrbind/clang_version.txt
  scripts/mrbind/clang_version_msys2.txt
  scripts/mrbind/generate.mk
  scripts/mrbind/install_deps_macos.sh
  scripts/mrbind/install_deps_ubuntu.sh
  scripts/mrbind/install_deps_windows_msys2.bat
  scripts/mrbind/install_mrbind_macos.sh
  scripts/mrbind/install_mrbind_ubuntu.sh
  scripts/mrbind/msys2_install_clang_ver.sh
Labels: full-ci, skip-image-rebuild

#3688 I5179 uniformity in examples
  doxygen/examples/MeshBoolean.dox
  doxygen/examples/MeshDecimate.dox
  doxygen/examples/MeshExport.dox
  doxygen/examples/MeshOffset.dox
  examples/c--sharp-example/MeshBoolean.dox.cs
  examples/c--sharp-example/MeshDecimate.dox.cs
  examples/c--sharp-example/Offset.dox.cs
  examples/c-examples/CMakeLists.txt
  examples/c-examples/MeshBoolean.dox.c
  examples/c-examples/MeshDecimate.dox.c
  examples/c-examples/MeshExport.dox.c
  examples/c-examples/MeshImportExport.dox.c
  examples/c-examples/MeshLoadSave.dox.c
  examples/c-examples/MeshOffset.dox.c
  examples/cpp-examples/MeshDecimate.dox.cpp
  examples/cpp-examples/MeshLoadSave.dox.cpp
  examples/cpp-examples/MeshOffset.dox.cpp
  examples/python-examples/MeshDecimate.dox.py
  examples/python-examples/MeshLoadSave.dox.py
  examples/python-examples/MeshOffset.dox.py
Labels: full-ci

#3718 raise exception if no dlls in nuget package
  .github/workflows/build-test-distribute.yml
  .github/workflows/build-test-windows.yml
  scripts/generate_nuget_spec.py
Labels: full-ci

#3721 Add coversion tests on new voxels format
  test_regression/test_conversion/test_conversion_points.py
Labels: upload-test-artifacts

#3738 Improve binding build times.
  .github/workflows/build-test-macos.yml
  .github/workflows/build-test-ubuntu-arm64.yml
  .github/workflows/build-test-ubuntu-x64.yml
  .github/workflows/build-test-windows.yml
  .github/workflows/pip-build.yml
  .github/workflows/prepare-images.yml
  scripts/mrbind/compiler_only_flags.txt
  scripts/mrbind/generate.mk
  scripts/mrbind/install_deps_ubuntu.sh
  scripts/mrbind/install_deps_windows_msys2.bat
  scripts/mrbind/mrbind_commit.txt
  scripts/mrbind/mrbind_flags.txt
  scripts/mrbind/mrbind_flags_for_helpers.txt
  source/MRMesh/MRObject.h
Labels: skip-image-rebuild
