Repository MeshInspector/MeshLib, pull requests merged in 2024-02, with the labels that each got.

#2168 Add test on boolean algorithm
  requirements/python.txt
  test_regression/helpers/meshlib_helpers.py
  test_regression/test_algorithms/test_boolean.py
  test_regression/test_doc_samples/test_boolean_sample.py
Labels: skip-image-rebuild

#2159 bump actions *-artifact from v3 to v4
  .github/workflows/build-test-distribute.yml
  .github/workflows/build-test-fedora.yml
  .github/workflows/build-test-macos.yml
  .github/workflows/build-test-ubuntu-arm64.yml
  .github/workflows/build-test-ubuntu20.yml
  .github/workflows/build-test-ubuntu22.yml
  .github/workflows/build-test-windows.yml
  .github/workflows/pip-build.yml
Labels: full-ci

#2269 Add offset autotest 2
  .github/workflows/build-test-fedora.yml
  .github/workflows/build-test-macos.yml
  .github/workflows/build-test-ubuntu-arm64.yml
  .github/workflows/build-test-ubuntu20.yml
  .github/workflows/build-test-ubuntu22.yml
  .github/workflows/build-test-windows.yml
  test_regression/helpers/meshlib_helpers.py
  test_regression/test_algorithms/test_offset.py
Labels: upload-test-artifacts
