Repository MeshInspector/MeshLib, pull requests merged in 2025-09, with the labels that each got.

#5035 CI: Add label for uploading binaries
  .github/workflows/config.yml
Labels: disable-build-windows, disable-build-ubuntu-arm64, disable-build-macos, disable-build-emscripten, upload-binaries

#5012 win ci: reduce usage
  .github/workflows/build-test-distribute.yml
  .github/workflows/build-test-windows.yml
  .github/workflows/config.yml
  .github/workflows/distro-release.yml
  .github/workflows/matrix/windows-finalize-release-config.json
  .github/workflows/matrix/windows-full-config.json
  .github/workflows/matrix/windows-minimal-config.json
  .github/workflows/matrix/windows-standard-config.json
  .github/workflows/update-win-version.yml
Labels: build-release-windows

#5105 macOS CMake: replace GTest::gtest with simple gtest
  source/MRMesh/CMakeLists.txt
  source/MRMesh/MRCircleObject.cpp
  source/MRMesh/MRMultiwayAligningTransform.cpp
  source/MRMesh/MRSphereObject.cpp
  source/MRTest/CMakeLists.txt
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-emscripten, disable-build-linux-vcpkg

#5108 build googletests as shared object on macOs
  thirdparty/CMakeLists.txt
Labels: skip-image-rebuild, disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-emscripten, disable-build-linux-vcpkg

#5113 Add point measurement object
  source/MRMesh/MRMesh.vcxproj
  source/MRMesh/MRMesh.vcxproj.filters
  source/MRMesh/MRPointMeasurementObject.cpp
  source/MRMesh/MRPointMeasurementObject.h
  source/MRMesh/MRPointObject.cpp
  source/MRMesh/MRPointObject.h
  source/MRViewer/MRRenderFeatureObjects.cpp
  source/MRViewer/MRRenderFeatureObjects.h
  source/MRViewer/MRRenderMeasurementObjects.cpp
  source/MRViewer/MRRenderMeasurementObjects.h
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg

#5146 Fix future vcpkg builds
  docker/rockylinux8-vcpkgDockerfile
  docker/rockylinux9-vcpkgDockerfile
  source/MeshLibC2/CMakeLists.txt
Labels: disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-macos, disable-build-emscripten
