Repository MeshInspector/MeshLib, pull requests merged in 2025-07, with the labels that each got.

#4789 fixed (potential) bug in PolylineToVoxels methods
  source/MRVoxels/MRPolylineToVoxels.cpp
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg

#4813 Make some external dependencies implicit
  examples/cpp-examples/CMakeLists.txt
  source/MRMesh/MRCNCMachineSettings.h
  source/MRMesh/MRConfig.cpp
  source/MRMesh/MRCylinderApproximator.h
  source/MRMesh/MRLog.cpp
  source/MRMesh/MRLog.h
  source/MRMesh/MRMeshBoolean.cpp
  source/MRMesh/MRTimer.cpp
  source/MRTest/MRTestApp.cpp
  source/MRViewer/MRGLMacro.h
  source/MRViewer/MRGLStaticHolder.cpp
  source/MRViewer/MRRenderFeatureObjects.cpp
  source/MRViewer/MRViewer.cpp
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-fedora, disable-build-macos, disable-build-linux-vcpkg

#4838 Downgrade vcpkg Linux host system to Rocky Linux 8
  .github/workflows/build-test-linux-vcpkg.yml
  .github/workflows/config.yml
  .github/workflows/prepare-images.yml
  cmake/Modules/CompilerOptions.cmake
  docker/rockylinux8-vcpkgDockerfile
  docker/rockylinux9-vcpkgDockerfile
  scripts/devops/release_table.txt
Labels: skip-image-rebuild, disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-macos, disable-build-emscripten

#4890 Add render ImGui to image function
  source/MRViewer/MRRenderImGuiToImage.cpp
  source/MRViewer/MRRenderImGuiToImage.h
  source/MRViewer/MRViewer.vcxproj
  source/MRViewer/MRViewer.vcxproj.filters
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-macos, disable-build-linux-vcpkg
