Repository MeshInspector/MeshLib, pull requests merged in 2025-08, with the labels that each got.

#4914 C bindings: Hide FloatGrid implementation
  scripts/mrbind/extra_headers/instantiate_templates.h
  source/MRTestC2/MRVDBConversions.c
  source/MRViewer/MRMarkedVoxelSlice.h
  source/MRVoxels/MRFloatGrid.cpp
  source/MRVoxels/MRFloatGrid.h
  source/MRVoxels/MRVDBFloatGrid.h
  source/MRVoxels/MRVoxelsFwd.h
  source/MRVoxels/MRVoxelsSave.cpp
  source/MRVoxels/MRVoxelsVolume.h
  source/mrviewerpy/MRPythonScene.cpp
Labels: disable-build-emscripten

#4920 Override visual object colors with tags
  source/MRCommonPlugins/ViewerButtons/MRAddCustomTheme.cpp
  source/MRMesh/MRObject.cpp
  source/MRMesh/MRObject.h
  source/MRMesh/MRObjectDistanceMap.cpp
  source/MRMesh/MRObjectDistanceMap.h
  source/MRMesh/MRObjectLinesHolder.cpp
  source/MRMesh/MRObjectLinesHolder.h
  source/MRMesh/MRObjectMeshHolder.cpp
  source/MRMesh/MRObjectMeshHolder.h
  source/MRMesh/MRObjectPointsHolder.cpp
  source/MRMesh/MRObjectPointsHolder.h
  source/MRMesh/MRString.cpp
  source/MRMesh/MRString.h
  source/MRMesh/MRVisualObject.cpp
  source/MRMesh/MRVisualObject.h
  source/MRViewer/MRViewer.vcxproj
  source/MRViewer/MRViewer.vcxproj.filters
  source/MRViewer/MRViewerSettingsManager.cpp
  source/MRViewer/MRVisualObjectTag.cpp
  source/MRViewer/MRVisualObjectTag.h
  source/MRVoxels/MRObjectVoxels.cpp
  source/MRVoxels/MRObjectVoxels.h
Labels: disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg

#4940 Fix Linux debug build
  source/MRSymbolMesh/CMakeLists.txt
Labels: full-ci, disable-build-windows, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg

#4938 Meshlib c getting started
  doxygen/general_pages/CSetupGuide.dox
  doxygen/general_pages/CppSetupGuide.dox
  doxygen/general_pages/GettingStarted.dox
  doxygen/layout_templates/base_struct.xml
  scripts/mrbind/README-generating.md
  scripts/mrbind/README.md
Labels: update-doc-only

#4963 VisualObjectTagManager: Register tags with custom id
  source/MRViewer/MRVisualObjectTag.cpp
  source/MRViewer/MRVisualObjectTag.h
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg

#4962 Fix VS project scripts for multi-dir structure
  .github/workflows/config.yml
  scripts/auto_update_vcxproj.py
  scripts/check_vcxproj.py
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg
