Repository MeshInspector/MeshLib, pull requests merged in 2025-06, with the labels that each got.

#4651 Update Tutorials.dox
  doxygen/general_pages/Tutorials.dox
Labels: update-doc-only

#4672 Upgrade Emscripten to 4.0.10
  docker/emscriptenDockerfile
  doxygen/general_pages/CppSetupGuide.dox
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-linux-vcpkg

#4703 fix bug in saving scene with distance map object
  source/MRMesh/MRObjectDistanceMap.h
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg

#4759 Force dragover to recalculate cursor position
  wasm/reset_events.js
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg

#4755 fixed cropped text in Modal window
  source/MRViewer/MRModalDialog.cpp
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg
