Repository MeshInspector/MeshLib, pull requests merged in 2025-01, with the labels that each got.

#3927 added flags to disable some builds
  .github/workflows/build-test-distribute.yml
  .github/workflows/config.yml
Labels: update-doc-only

#3970 Update python setup dox
  doxygen/PythonSetupGuide.dox
Labels: update-doc-only

#3984 Documentation juggling
  doxygen/.gitignore
  doxygen/common_files/CommonDistributionProperties.dox
  doxygen/examples/MeshLoadSave.dox
  doxygen/general_pages/APIPage.dox
  doxygen/general_pages/About.dox
  doxygen/general_pages/CSharpSetupGuide.dox
  doxygen/general_pages/CmakeSetupGuide.dox
  doxygen/general_pages/CppSetupGuide.dox
  doxygen/general_pages/DataModel.dox
  doxygen/general_pages/FirstPluginTutorial.dox
  doxygen/general_pages/GettingStarted.dox
  doxygen/general_pages/License.dox
  doxygen/general_pages/PackageOverview.dox
  doxygen/general_pages/PythonSetupGuide.dox
  doxygen/general_pages/Spaces.dox
  doxygen/general_pages/StatePluginsHelp.dox
  doxygen/general_pages/ThirdpartyList.dox
  doxygen/general_pages/Tutorials.dox
  doxygen/layout_templates/base_struct.xml
  scripts/doxygen/generate_doxygen_layout.sh
Labels: update-doc-only

#3987 Fix mesh decimate issue
  source/MRMesh/MRMeshDecimate.cpp
Labels: upload-test-artifacts

#3991 add ubuntu24 GCC Release build, create rpm from Clang-17
  .github/workflows/build-test-fedora.yml
  .github/workflows/matrix/ubuntu-x64-minimal-config.json
Labels: full-ci

#3993 Try disabling `std::expected`.
  .github/workflows/build-test-macos.yml
  .github/workflows/pip-build.yml
  source/MRMesh/MRExpected.h
Labels: test-pip-build

#3997 Doc: Update C++ and Python examples
  doxygen/examples/FreeFormDeformation.dox
  doxygen/examples/GlobalRegistration.dox
  doxygen/examples/LaplacianExample.dox
  doxygen/examples/MeshFromText.dox
  doxygen/examples/MeshResolveDegenerations.dox
  doxygen/examples/NoiseDenoiseExample.dox
  doxygen/examples/Triangulation.dox
  examples/cpp-examples/CMakeLists.txt
  examples/cpp-examples/FreeFormDeformation.dox.cpp
  examples/cpp-examples/GlobalRegistration.dox.cpp
  examples/cpp-examples/LaplacianDeformation.dox.cpp
  examples/cpp-examples/MeshLoadSave.dox.cpp
  examples/cpp-examples/MeshModification.dox.cpp
  examples/cpp-examples/MeshResolveDegenerations.dox.cpp
  examples/cpp-examples/NoiseDenoise.dox.cpp
  examples/cpp-examples/Triangulation.dox.cpp
  examples/python-examples/MeshFromText.dox.py
  examples/python-examples/MeshResolveDegenerations.dox.py
Labels: update-doc

#3990 Decimate mesh: update queue periodically
  .github/actions/python-regression-tests/action.yml
  source/MRMesh/MRMesh.vcxproj
  source/MRMesh/MRMesh.vcxproj.filters
  source/MRMesh/MRMeshDecimate.cpp
  source/MRMesh/MRPriorityQueue.h
Labels: upload-test-artifacts

#4019 reworked workflow logic (update-doc dependence) to avoid always failed rerun
  .github/workflows/build-test-distribute.yml
  .github/workflows/build-test-ubuntu-arm64.yml
  .github/workflows/pip-build.yml
  .github/workflows/update-docs.yml
Labels: update-doc, disable-build-windows, disable-build-ubuntu-x64, disable-build-fedora, disable-build-macos, disable-build-emscripten

#4028 Add float vs double dox page
  doxygen/general_pages/FloatVSDouble.dox
  doxygen/layout_templates/base_struct.xml
Labels: update-doc-only
