Repository MeshInspector/MeshLib, pull requests merged in 2025-04, with the labels that each got.

#4356 update nuget patch to update targets file too
  .github/workflows/build-test-distribute.yml
  scripts/nuget_package_patch.py
  scripts/nuget_patch/nuget_package_patch.py
Labels: full-ci, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten

#4335 Wasm: Enable Node.js support
  cmake/Modules/CompilerOptions.cmake
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos

#4355 CMake: Build imgui as a subproject
  CMakeLists.txt
  cmake/Modules/CompilerOptions.cmake
  meshlib-config.cmake.in
  source/MRPch/CMakeLists.txt
  source/imgui/CMakeLists.txt
  source/imgui/MRCustomImGuiConfig.cpp
  source/imgui/MRCustomImGuiConfig.h
  source/imgui/imgui.vcxproj
  source/imgui/imguiConfig.cmake
  source/mrviewerpy/CMakeLists.txt
  thirdparty/CMakeLists.txt
Labels: skip-image-rebuild

#4372 pip-build: set CMAKE_POLICY_VERSION_MINIMUM: 3.5
  .github/workflows/pip-build.yml
Labels: skip-image-rebuild, test-pip-build, disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten

#4261 Add test on Nuget package
  .github/workflows/build-test-distribute.yml
  .github/workflows/sign-upload-nuget.yml
  .github/workflows/unity-nuget-test.yml
Labels: full-ci, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten

#4391 Add more options in sign upload nuget script
  .github/workflows/sign-upload-nuget.yml
  scripts/nuget_patch/nuget_make_beta.py
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten

#4383 Try build NUGET with linux support
  .github/workflows/build-test-distribute.yml
  .github/workflows/build-test-ubuntu-x64.yml
  .github/workflows/build-test-windows.yml
  scripts/nuget_patch/fake_whl_helper.py
  scripts/nuget_patch/nuget_package_patch.py
  scripts/nuget_patch/patch_linux_so.py
Labels: full-ci, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten

#4403 Make NuGet with correct runtime structure
  .github/workflows/build-test-distribute.yml
  .github/workflows/build-test-ubuntu-x64.yml
  .github/workflows/build-test-windows.yml
  scripts/generate_nuget_spec.py
  scripts/nuget_patch/generate_nuget_spec.py
  scripts/nuget_patch/nuget_package_patch.py
  scripts/nuget_patch/patch_library_deps.py
  scripts/nuget_patch/patch_linux_so.py
  scripts/nuget_patch/template.nuspec
Labels: full-ci, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten

#4404 gh release download instead of robinraju/release-downloader
  .github/workflows/build-test-distribute.yml
  .github/workflows/test-distribution.yml
Labels: full-ci

#4428 Unity test: clean up local nupkg
  .github/workflows/unity-nuget-test.yml
Labels: full-ci, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg

#4437 Download unity nuget pkg from releases instead of s3
  .github/workflows/build-test-distribute.yml
  .github/workflows/config.yml
  .github/workflows/unity-nuget-test.yml
Labels: full-ci

#4376 Add test and sample on variable offset
  doxygen/examples/Examples.dox
  doxygen/examples/MeshOffsetWeighted.dox
  examples/python-examples/MeshOffsetWeighted.dox.py
  test_regression/test_algorithms/test_offset.py
  test_regression/test_doc_samples/test_python_samples.py
Labels: update-doc

#4401 Add instance state check before starting EC2 instances
  .github/workflows/unity-nuget-test.yml
Labels: full-ci, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten

#4460 readme/update-readme-file
  readme.md
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg

#4464 Doc: Update CMake setup guide
  .github/workflows/build-test-distribute.yml
  doxygen/general_pages/CmakeSetupGuide.dox
Labels: update-doc-only

#4449 Replace obsolete function
  .github/actions/python-regression-tests/action.yml
  doxygen/DoxygenLayout.xml
  doxygen/examples/Examples.dox
  doxygen/examples/MeshResolveDegenerations.dox
  doxygen/layout_templates/base_struct.xml
  examples/c-examples/CMakeLists.txt
  examples/c-examples/MeshFixDegeneracies.dox.c
  examples/c-sharp-examples/MeshFixDegeneracies.dox.cs
  examples/c-sharp-examples/MeshResolveDegenerations.dox.cs
  examples/cpp-examples/CMakeLists.txt
  examples/cpp-examples/MeshFixDegeneracies.dox.cpp
  examples/python-examples/MeshFixDegeneracies.dox.py
  source/MRDotNet/MRMeshDecimate.cs
  source/MRDotNet/MRMeshFixer.cs
  source/MRMeshC/MRMeshFixer.cpp
  source/MRMeshC/MRMeshFixer.h
  test_regression/test_doc_samples/test_c_sharp_samples.py
Labels: full-ci

#4346 rootless arm builds
  .github/workflows/build-test-ubuntu-arm64.yml
  .github/workflows/build-test-ubuntu-x64.yml
  .github/workflows/pip-build.yml
  .github/workflows/release-tests.yml
  .github/workflows/update-docs-manual.yml
  docker/ubuntu20Dockerfile
  docker/ubuntu22Dockerfile
  docker/ubuntu24Dockerfile
  scripts/mrbind-pybind11/install_all_python_versions_ubuntu_pkgs.sh
  scripts/mrbind-pybind11/install_all_python_versions_ubuntu_reqs.sh
  scripts/run_python_test_script.py
Labels: test-pip-build, disable-build-windows, disable-build-ubuntu-x64, disable-build-fedora, disable-build-macos, disable-build-emscripten

#4474 Update pyhon setup page
  doxygen/general_pages/PythonSetupGuide.dox
Labels: update-doc-only

#4475 Doc: Update C++ setup guide
  doxygen/general_pages/CppSetupGuide.dox
Labels: update-doc-only

#4477 Fix Package Overview list
  doxygen/general_pages/PackageOverview.dox
  doxygen/layout_templates/base_struct.xml
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg

#4476 Doc: Update C# setup guide
  doxygen/general_pages/CSharpSetupGuide.dox
Labels: update-doc-only

#4484 docs: the latest vcpkg version is available for vs22
  doxygen/general_pages/CppSetupGuide.dox
Labels: update-doc-only

#4496 Restore old readme page
  readme.md
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg

#4506 Doc: Add C++ code samples
  .github/workflows/build-test-ubuntu-arm64.yml
  .github/workflows/build-test-ubuntu-x64.yml
  examples/cpp-samples/CMakeLists.txt
  examples/cpp-samples/GlobalRegistration.cpp
  examples/cpp-samples/LaplacianDeformation.cpp
  source/MRMesh/MRLaplacian.h
  source/MRMesh/MRMultiwayICP.h
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-fedora, disable-build-macos, disable-build-emscripten, disable-build-linux-vcpkg
