Repository MeshInspector/MeshLib, pull requests merged in 2025-03, with the labels that each got.

#4233 restore compatibility with CMake from VS2019
  .github/workflows/build-test-windows.yml
  CMakeLists.txt
  source/MRCommonPlugins/CMakeLists.txt
  source/MREmbeddedPython/CMakeLists.txt
  source/MRTest/CMakeLists.txt
  source/MRViewer/CMakeLists.txt
Labels: full-ci, skip-image-rebuild

#4272 Add samples on signed distance
  doxygen/examples/Examples.dox
  doxygen/examples/SignedDistance.dox
  doxygen/examples/SignedDistancePointToMesh.dox
  examples/python-examples/SignedDistance.dox.py
  examples/python-examples/SignedDistancePointToMesh.dox.py
  test_regression/test_algorithms/test_signed_dist.py
Labels: update-doc

#4259 Wasm: Update Emscripten to 4.0.5
  docker/emscriptenDockerfile
  source/MRMesh/MRphmap.h
  source/MRViewer/wasm_async_func_list.txt
Labels: skip-image-rebuild, disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos

#4274 Add samples on signed distances
  doxygen/examples/Examples.dox
  doxygen/examples/SignedDistances
  examples/python-examples/SignedDistances.dox.py
  test_regression/test_algorithms/test_signed_distances.py
Labels: update-doc

#4290 Add free form deformer bindings for C#
  doxygen/examples/FreeFormDeformation.dox
  examples/c-sharp-examples/FreeFormDeformation.dox.cs
  source/MRDotNet/MRFreeFormDeformer.cs
  source/MRDotNet/MRMesh.cs
  source/MRDotNet/MRVector3.cs
Labels: update-doc

#4292 CI: Use commit SHAs instead of tags for actions
  .github/actions/python-regression-tests/action.yml
  .github/workflows/build-test-distribute.yml
  .github/workflows/build-test-windows.yml
  .github/workflows/config.yml
  .github/workflows/pip-build.yml
  .github/workflows/prepare-images.yml
  .github/workflows/test-distribution.yml
  .github/workflows/update-app-container.yml
  .github/workflows/update-docs-manual.yml
  .github/workflows/update-docs.yml
  .github/workflows/versioning-release.yml
Labels: full-ci

#4321 Add patch for nuget package
  .github/workflows/build-test-distribute.yml
  scripts/nuget_package_patch.py
Labels: full-ci, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos, disable-build-emscripten

#4072 ubuntu24: introduce gcc-14 but without nvcc
  .github/workflows/build-test-ubuntu-x64.yml
  .github/workflows/matrix/ubuntu-x64-full-config.json
  .github/workflows/matrix/ubuntu-x64-minimal-config.json
  .github/workflows/test-distribution.yml
  docker/ubuntu24Dockerfile
  scripts/distribution.sh
  source/MRMesh/MRMeshFwd.h
Labels: full-ci, skip-image-rebuild

#4333 Doc: Update Emscripten guide
  doxygen/general_pages/CppSetupGuide.dox
  scripts/devops/release_table.txt
Labels: update-doc-only

#4338 Wasm: Show info about 64-bit version
  source/MRMesh/MRSystem.cpp
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-macos

#4340 Switch from gtkmm 3 to GTK 3
  requirements/macos.txt
  source/MRViewer/CMakeLists.txt
  source/MRViewer/MRFileDialog.cpp
Labels: disable-build-windows, disable-build-emscripten

#4344 CI/CD: Run Start-and-Exit Tests on all macOS
  .github/workflows/build-test-macos.yml
Labels: disable-build-windows, disable-build-ubuntu-x64, disable-build-ubuntu-arm64, disable-build-fedora, disable-build-emscripten
